myrsync: Add option -y for nonstop run

diff --git a/bin/myrsync b/bin/myrsync
--- a/bin/myrsync
+++ b/bin/myrsync
@@ -14,23 +14,41 @@ line=$(printf '%*s\n' "$columns" '' | tr ' ' -)
 
 sync() {
   echo ""
-  echo "$ $rsynccmd -n $1 $2"
-  echo "$line"
-  $rsynccmd -n $1 $2
-  echo "$line"
-  read -p "Continue? [y/N]" confirm
-  if [ "$confirm" != "y" ]; then
-    echo "Aborted."
-    exit 1
+  if $confirm; then
+    echo "$ $rsynccmd -n $1 $2"
+    echo "$line"
+    $rsynccmd -n $1 $2
+    echo "$line"
+    read -p "Continue? [y/N]" confirm
+    if [ "$confirm" != "y" ]; then
+      echo "Aborted."
+      exit 1
+    fi
+    echo ""
   fi
-  echo ""
   echo "$ $rsynccmd $1 $2"
   echo "$line"
   $rsynccmd $1 $2
 }
 
+confirm=true
+
+while getopts y OPT
+do
+  case $OPT in
+    "y") confirm=false
+      ;;
+    *)
+      echo "myrsync: Unknown option."
+      exit 1
+      ;;
+  esac
+done
+
+shift
+
 if [ "$1" = 'up' ]; then
-  sync $localpath $dropboxpath
+  sync $localpath $dropboxpath 
 elif [ "$1" = 'down' ]; then
   sync $dropboxpath $localpath
 else
